# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='addthis_use_author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='addthis_username',
        ),
        migrations.RemoveField(
            model_name='article',
            name='auto_tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='followup_for',
        ),
        migrations.RemoveField(
            model_name='article',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_articles',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rendered_content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='use_addthis_button',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
